### PR TITLE
fix(pg): Fixed error logs for multi node cron jobs.

### LINKED ISSUE #76: Multi node cron jobs.
At the moment if you were to start a neoq worker on 2 different nodes with a single PostgreSQL backend and have crons configured for them. 

Every time a cron would be scheduled, one node will ultimately insert the cron into the jobs table while the other nodes fail with an error `level=ERROR msg="error queueing cron job" error="duplicate job"`.

Is the intended use case that a single node would orchestrate the enqueuing of these crons? Or that the contention and resulting error about duplicate job from the additional nodes is intended?

### PR DESCRIPTION
**Pull request by elliotcourant**
When multiple nodes were participating as workers and a cron job was to
be enqueued, all nodes would attempt to enqueue it at the same time. As
a result all but one node would successfully enqueue the job and the
other nodes would log a message about a duplicate job. In any other
scenario this would be a log that would be good to surface, but it is
not a significant error message here as the job was still enqueued
properly.

Resolves #76

---

@acaloiaro Thoughts on testing this? I could add a test for just a multi node cron job in general and assert that it is
only performed once with multiple workers. But actually asserting that the log is not shown anymore doesn't seem like a
useful test? Let me know what your thoughts are.

### CODE REVIEW

File: backends/postgres/postgres_backend_test.go [hunk 1]
```diff
@@ -410,6 +410,71 @@ func TestCron(t *testing.T) {
 	})
 }
 
+func TestMultipleCronNodes(t *testing.T) {
+	jobsProcessed := sync.Map{}
```
Comment (elliotcourant) [inline backends/postgres/postgres_backend_test.go:414]: I ended up switching to this over a channel so that I can detect duplicate job consumption by the job ID. Since we know that only one job can be inserted at a time for a given cron, we need to make sure that that one job is only consumed once.

The test just checks to see that when the job is processed, it hasn't already been consumed by someone else.

File: backends/postgres/postgres_backend_test.go [hunk 2]
```diff
@@ -410,6 +410,71 @@ func TestCron(t *testing.T) {
...
+		err = nq.StartCron(ctx, cron, h)
+		if err != nil {
+			t.Error(err)
+		}
+
+		workers[i] = nq
+	}
+
+	// allow time for listener to start and for at least one job to process
+	time.Sleep(2 * time.Second)
```
Comment (elliotcourant) [inline backends/postgres/postgres_backend_test.go:468]: We could really wait as long as we want here, the longer it runs the more crons get processed and the more we assert that we don't have duplicates. But I don't want to introduce a long running test for the sake of having a long running test. Up to you if you want to have this run longer?

Comment (acaloiaro) [reply backends/postgres/postgres_backend_test.go:468]: It will be preferable to bump `numberOfWorkers` up so that we can test more enqueueing events in the smallest amount of time possible. Is 50 realistic? We may bump into Github's 100 connections per PG server limit at some point; there's a way to change that limit, but it's a little ugly.

I would also drop that sleep time down to something like `1050 * time.Millisecond` and give the `Duration` a name like `SlightlyMoreThanOneSecond`.

File: backends/postgres/postgres_backend.go [hunk 3]
```diff
@@ -220,6 +220,10 @@ func txFromContext(ctx context.Context) (t pgx.Tx, err error) {
 
 // initializeDB initializes the tables, types, and indices necessary to operate Neoq
 //
+// This will consume the migration files embedded at build time and will connect to the DB using it's own tooling and
+// perofmr the migrations. After which it will close it's DB connections since they will not be needed after
```
Comment (acaloiaro) [inline backends/postgres/postgres_backend.go:224]: Typo: `perofmr` -> `perform`, `it's` -> `its`

File: backends/postgres/postgres_backend_test.go [hunk 4]
```diff
@@ -404,22 +374,72 @@ func TestCron(t *testing.T) {
...
+	if jobsCompleted == 0 {
+		t.Fatalf("no jobs were completed after 2 seconds?")
```
Comment (acaloiaro) [inline backends/postgres/postgres_backend_test.go:429]: See above comment, and then we can change this to:

`t.Fatalf("no jobs were completed after %v", SlightlyMoreThanOneSecond)`

File: backends/postgres/postgres_backend_test.go (hunk 2 above)
Comment (elliotcourant) [reply backends/postgres/postgres_backend_test.go]: Added!

File: backends/postgres/postgres_backend.go (hunk 3 above)
Comment (elliotcourant) [reply backends/postgres/postgres_backend.go]: Thank you, someday I'll figure out how to get grammarly working properly as an LSP.

File: backends/postgres/postgres_backend_test.go (hunk 4 above)
Comment (elliotcourant) [reply backends/postgres/postgres_backend_test.go]: Updated!

**Review by acaloiaro — APPROVED** [review]
Good to go.
